sudo: required
dist: trusty
language: node_js
node_js:
- '6'
git:
  depth: 3
cache:
  directories:
  - Tools/Gulp/node_modules
  - Playground/node_modules
  - tests/unit/node_modules
install:
- travis_retry npm install -g gulp
- cd ./Tools/Gulp
- travis_retry npm install
jobs:
  include:
  - stage: BabylonJS Build and test
    env: JOB=WhatsNewUpdate
    script: gulp tests-whatsnew
  - env: JOB=DocumentationCheck
    script: gulp typedoc-check
  - env: JOB=Build
    script: gulp typescript-all
  - env: JOB=Tests
    script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    - set -e
    - gulp typescript-all
    - gulp typedoc-all
    - gulp tests-unit
    - travis_retry gulp tests-validation-virtualscreen
    - travis_retry gulp tests-validation-browserstack
notifications:
  slack:
    secure: U5Z8IyrnweEQjkuqilARavJlcBwvwAv/PAMCgJpNRA2winRxJBnd+2rc7mhlsTYNbhqj/wXU2DZa+RXhfmmE8WCr7DhQDv5UJL3mHKa8NouIivWTK6YkYfDiIoKuGONwNAzlF3Eq+U6AwLb1Wg8MSnxrb/+mafQ7VWVXB/O0wqg=
env:
  global:
  - secure: REbDQYeYzixPtubdYamQo4yakPJd3XnEE1k8QpVC3Kn6f6WOV/9+/C4crdi7fGQYJUg6QNCW3FnWch6+kTgAF1ad9AcHZ77Rwj+weEXlhPJer53oWXIiSAR33NOR1cDo/+76WfIDT551oQ6EccaQbB4SqDFd3v8px/eV5/dIMPo=
  - secure: VJCeEBtUlKX4pXEW9ey2D7MuK2agYxNHyimzZSy5SYiL90mp3UN+JUb2sTJRYbRBGSTgPdVoEKDDzDCuhGBds9HKj/IccZ1jKYzhJNKCZg7NZaVsqRhdsyWWTGgfHnvEGtgqYCjp8b8XyMLOdR/WYarXhHTURZqmTNQ7kUJPOYo=
