trigger:
- preview

jobs:
- job: NetlifyStaticDeploy
  displayName: 'Deploy'
  pool:
    vmImage: 'Ubuntu-16.04'
    demands: npm
  steps:
  - script: 'npm install netlify'
    displayName: 'npm install netlify'
  - script: 'npx netlify link --id=220a52f0-ea85-4244-8342-8ec149cd78d6'
    displayName: 'netlify link babylonjscontrollers'
    env:
      AZURE_PULLREQUESTID: $(System.PullRequest.PullRequestId)
      NETLIFY_AUTH_TOKEN: $(babylon.netlify.authToken)
  - script: 'npx netlify deploy --prod --dir=assets/meshes/controllers'
    displayName: 'netlify link babylonjscontrollers'
    env:
      AZURE_PULLREQUESTID: $(System.PullRequest.PullRequestId)
      NETLIFY_AUTH_TOKEN: $(babylon.netlify.authToken)
